server:
  port: 8082

spring:
  mvc:
    pathmatch:
      # 解决SpringBoot高版本(2.6以上) swagger-ui报错的问题
      matching-strategy: ANT_PATH_MATCHER

  # 配置nacos
  application:
    name: example-service2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848